### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by alanpjohn** [ARgorithm/Unity-App#3]
## Connecting to ARgorithmServer

The `APIClient` class has to be created whose functions will be called by button manager
functions that will be required: 
- `connect` : to connect to server and check if auth is required
- `create` : to create user account
- `authenticate` : to authenticate user credentials and store JWT token
- `list` : gets list of argorithms from connected server
- `run` : gets states from server after execution

**Comment by alanpjohn** [comment]
A very good repo i found as [reference](https://github.com/dilmerv/UnityRestClient/blob/master/Assets/RestClient/Scripts/RestClientGetAndPostExample.cs)

So regarding the web API

I am making a class called `APIclient` which will have methods you will call like how in the above link the developer calls the routine. you have to catch the callback which will have the data you will need. I'll make classes for Responses which will make it easier for you to take data from them
something like this

```cs
    void onclick()
    {
        // send a get request
        StartCoroutine(APIClient.connect(ip_addr, (r) => OnRequestComplete(r)));
    }

    void OnRequestComplete(ConnectionResponse r)
    {
        Debug.Log($"Status: {r.status}");
    }
```

for `connect`
It'll return a `ConnectionResponse` with one member that is `status:string`.

for `create`
It'll take input in as a `AccountRequest` object which will have two members `email` and `password` and return a `AuthResponse` which will have the `jwtToken:string` and `status:string` , similarly for `login`

for `list`
It'll return a `List<ARgorithmResponse>` which you can use to generate your list, each `ARgorithmResponse` will have all the details of ARgorithm, (check in Toolkit or Server)

for `run`
It'll take a `ExecutionRequest`  as input and give a json file as output which you will forward to the parser

you can either wait a day for me to finish this or you can create your own dummy client to test functions
in case you use dummy functions, *Do not push them*

**Comment by Vin-dictive** [comment]
Understood.
