### ISSUE TITLE
Button Manager

### ISSUE THREAD

**Issue by alanpjohn** [ARgorithm/Unity-App#4]
## Implementation of Login UI

Login UI has to be implemented
![image](https://user-images.githubusercontent.com/35735486/106423008-99e0b300-6485-11eb-83f5-071e13c72451.png)

## ButtonManager

All UI transition and actions will go through the button manager and it will call the functions of `APIClient`.(#3) 
The button manager should take hardcoded input from API calls till the `APIClient` is ready

**Comment by alanpjohn** [comment]
@Vin-dictive 
remember to validate email and password as the user enters it
email should be a valid email
password should follow the regex pattern `^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,25}$`

**Comment by Vin-dictive** [comment]
I will do the changes immediately. For now I am able to validate the entered password and re entered password. I will make the above changes as well.
